### ISSUE TITLE
Even out the heights of city cards

### ISSUE THREAD

**Issue by jonathanyeong** [mikejahn/support-your-local-businesses#13]
This may be an issue with unsplash image sending back images with different dimensions. It looks like we'll need to set a max height to the cards.

<img width="1792" alt="Screen Shot 2020-03-17 at 10 21 36 AM" src="https://user-images.githubusercontent.com/3861088/76883339-3df34880-6839-11ea-898f-cf0df0a4ce3f.png">

**Comment by mikejahn** [comment]
Fixed now, so closing issue.
