### ISSUE TITLE
Add bootstrap styles to "New City" form

### ISSUE THREAD

**Issue by jonathanyeong** [mikejahn/support-your-local-businesses#15]
Let's add bootstrap styles to this form, to keep this consistent with the "New Business" form.

<img width="1792" alt="Screen Shot 2020-03-17 at 10 28 01 AM" src="https://user-images.githubusercontent.com/3861088/76883885-0769fd80-683a-11ea-9ae2-f33f83a27796.png">

**Comment by MattAdelberger** [comment]
I can take this issue

**Comment by mikejahn** [comment]
@MattAdelberger I actually fixed this and added some more styling based off your original styling.
