### ISSUE TITLE
Setup SSL certificate for https

### ISSUE THREAD

**Issue by jonathanyeong** [mikejahn/support-your-local-businesses#7]
Fix the connection not secure message.

<img width="547" alt="Screen Shot 2020-03-16 at 8 48 57 PM" src="https://user-images.githubusercontent.com/3861088/76820252-d8b33f00-67c7-11ea-8349-aa81c8383f2f.png">

**Comment by mikejahn** [comment]
It is already set up in DNSimple and uploaded to Heroku.  I think we just need to ensure http redirects to https.

ie: https://supportyourlocalbusinesses.com works but http://supportyourlocalbusinesses.com should redirect to https://supportyourlocalbusinesses.com

**Comment by mikejahn** [comment]
@jonathanyeong

**Comment by jonathanyeong** [comment]
Ah gotcha! I'll leave that to you then @mikejahn
